# Generated by Django 5.1.6 on 2025-02-21 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_alter_post_options_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Posts', 'verbose_name_plural': 'Posts'},
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
